import Head from 'next/head'
import { useEffect } from 'react'
import { isMobile } from 'react-device-detect'
import AboutSection from '../components/Homepage/AboutSection'
import CarouselSection from '../components/Homepage/CarouselSection'
import HeaderSection from '../components/Homepage/HeaderSection'
export default function Home() {



  useEffect(()=>{


  },[])

  

  return (
    <div className='overflow-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSection/>
      <AboutSection/>
      <CarouselSection/>
      
    </div>
  )
}
